#!/usr/bin/env bash

if [[ -z "$DOTFILES_DIR" ]]; then
	echo "DOTFILES_DIR variable is not set. Set it manually or use bootstrap.sh to install these dotfiles."
	exit 1;
fi;

OS="$(uname)"

# Aliases
if [[ $OS != "Darwin" ]]; then
	alias ls='ls --color=auto'
fi;

alias grep='grep --color=auto'
alias diff='diff --color=auto'
alias dmesg="dmesg --color=always"
alias radio10="mplayer http://stream.radio10.nl/radio10"


# Environment vars
PATH="$PATH:$DOTFILES_DIR/bin"
PATH="$PATH:$HOME/.local/bin"

if [[ -d "$HOME/.gem/ruby/2.7.0/bin" ]]; then
	PATH="$PATH:$HOME/.gem/ruby/2.7.0/bin"
fi;

# Pretty bash prompt
source "$DOTFILES_DIR/bash/bash_prompt"

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob;

# Append to the Bash history file, rather than overwriting it
shopt -s histappend;

# Expand variables on TAB
shopt -s direxpand

# Autocorrect typos in path names when using `cd`
shopt -s cdspell;

# Enable some Bash 4 features when possible:
# * `autocd`, e.g. `**/qux` will enter `./foo/bar/baz/qux`
# * Recursive globbing, e.g. `echo **/*.txt`
for option in autocd globstar; do
	shopt -s "$option" 2> /dev/null;
done;

# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
[ -e "$HOME/.ssh/config" ] && complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2- | tr ' ' '\n')" scp sftp ssh;

# Source autojump - https://github.com/wting/autojump
[ -e "/etc/profile.d/autojump.bash" ] && source /etc/profile.d/autojump.bash
